fail_fast: true
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/hadialqattan/pycln
    rev: "v1.1.0"
    hooks:
      - id: pycln
  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: mypy
        name: typechecking
        pass_filenames: false
        always_run: true
        language: script
        entry: .venv/bin/mypy --install-types --non-interactive
      - id: pytest-cov
        name: pytest-cov
        pass_filenames: false
        language: script
        stages: [push]
        types_or: [python, toml]
        entry: .venv/bin/pytest --cov csgoinvshuffle --cov-report html:coverage
