repos:
  - repo: https://github.com/jvllmr/pyaphid
    rev: v0.1.4
    hooks:
      - id: pyaphid
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.1.2"
    hooks:
      - id: pycln
  - repo: https://github.com/PyCQA/isort
    rev: "5.11.4"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest-cov
        pass_filenames: false
        language: script
        stages: [push]
        types_or: [python, toml]
        entry: .venv/bin/pytest --cov csgoinvshuffle --cov-report html:coverage
