repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.1.1"
    hooks:
      - id: pycln
  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest-cov
        pass_filenames: false
        language: script
        stages: [push]
        types_or: [python, toml]
        entry: .venv/bin/pytest --cov csgoinvshuffle --cov-report html:coverage
